In [1]:
import pandas as pd
df = pd.read_csv('full-data.csv')
df.head()

,T101,T102,T103,T104,T105,T106,T107,T108,T109,T110,...,T205,T206,T207,T208,T209,T210,T211,T212,T301,mode
0,0.637017,-0.225090,0.055348,0.744241,-0.084037,0.055404,0.525860,-0.037552,-0.147165,0.770602,...,-0.917000,-0.064527,0.827770,-0.955300,-0.466759,-0.718640,-0.762272,0.253723,4762.852632,walking
1,0.726260,-0.106946,-0.110581,-0.002687,-0.005291,-0.007923,0.223897,0.305277,0.053001,0.701905,...,0.718242,-0.132853,0.763585,-0.902233,-0.583210,-0.472734,-0.876121,0.231781,6321.615789,walking
2,0.926454,-0.302304,-0.054040,0.433587,0.176344,-0.283395,0.469788,0.233726,-0.530212,0.604623,...,-0.109107,0.204693,0.645861,-0.862494,-0.494675,-0.206425,-0.829928,0.086118,4269.086842,walking
3,0.585084,-0.113394,0.149108,0.201162,0.196460,0.018323,0.242608,-0.182433,-0.014732,0.752332,...,0.449368,0.381364,0.811386,-0.750908,-0.403719,-0.288068,-0.665273,-0.126024,5315.044737,walking
4,0.819980,-0.181248,-0.152334,0.980922,-0.163211,-0.190165,0.549710,0.123823,-0.085992,0.640439,...,0.946671,0.814770,0.780156,-0.878388,-0.471263,-0.430760,-0.774618,0.056458,6025.284211,walking

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 38 columns):
T101    97 non-null float64
T102    97 non-null float64
T103    97 non-null float64
T104    97 non-null float64
T105    97 non-null float64
T106    97 non-null float64
T107    97 non-null float64
T108    97 non-null float64
T109    97 non-null float64
T110    97 non-null float64
T111    97 non-null float64
T112    97 non-null float64
T113    97 non-null float64
T114    97 non-null float64
T115    97 non-null float64
T116    97 non-null float64
T117    97 non-null float64
T118    97 non-null float64
T119    97 non-null float64
T120    97 non-null float64
T121    97 non-null float64
T122    97 non-null float64
T123    97 non-null float64
T124    97 non-null float64
T201    97 non-null float64
T202    97 non-null float64
T203    97 non-null float64
T204    97 non-null float64
T205    97 non-null float64
T206    97 non-null float64
T207    97 non-null float64
T208    97 non-null float64
T209    97 non-null float64
T210    97 non-null float64
T211    97 non-null float64
T212    97 non-null float64
T301    97 non-null float64
mode    97 non-null object
dtypes: float64(37), object(1)
memory usage: 28.9+ KB

In [9]:
import numpy as np
df.describe(include=[np.number])

,T101,T102,T103,T104,T105,T106,T107,T108,T109,T110,...,T204,T205,T206,T207,T208,T209,T210,T211,T212,T301
count,97.000000,97.000000,97.000000,97.000000,9.700000e+01,97.000000,97.000000,97.000000,97.000000,97.000000,...,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,0.327232,-0.080190,-0.017873,0.262808,-3.675680e-02,-0.046021,0.248738,-0.048656,-0.037453,0.338196,...,0.142964,0.022251,0.293418,0.584037,-0.009127,0.126363,0.124130,-0.212687,-0.010313,2016.847911
std,0.416630,0.191221,0.117575,0.386595,1.463160e-01,0.139180,0.393564,0.245937,0.206101,0.478841,...,0.396342,0.492197,0.384170,0.414107,0.659458,0.702201,0.504938,0.632737,0.484546,3090.657552
min,-0.062784,-0.791517,-0.326019,-0.626171,-6.267154e-01,-0.394707,-0.970606,-0.630252,-0.579377,-0.900000,...,-0.866615,-0.917000,-0.678551,-0.253629,-0.958433,-0.962474,-0.811453,-0.953033,-0.982301,0.781579
25%,-0.002687,-0.081919,-0.022513,-0.002687,-8.403671e-02,-0.126331,-0.055797,-0.190459,-0.150392,-0.013480,...,-0.096374,-0.280976,-0.013774,0.114708,-0.733341,-0.479391,-0.253629,-0.780707,-0.168345,4.600000
50%,-0.002687,-0.005291,-0.007923,0.097967,-5.291079e-03,-0.007923,0.242608,-0.056104,-0.027255,0.265178,...,0.166667,0.031607,0.280976,0.763585,0.052632,-0.114708,0.052632,-0.150188,0.052632,96.276316
75%,0.716732,-0.005291,-0.007923,0.542713,-1.940000e-16,-0.007923,0.548850,0.123823,0.093200,0.727209,...,0.350438,0.293385,0.656437,0.948557,0.497364,1.000000,0.471405,0.114708,0.187317,4279.031579
max,1.267589,0.280529,0.369137,1.201411,3.596901e-01,0.408697,1.138020,0.678006,0.406848,1.376387,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,19410.952630

In [17]:
df1 = df[['T301','mode']]
df1.head()

          T301     mode
0  4762.852632  walking
1  6321.615789  walking
2  4269.086842  walking
3  5315.044737  walking
4  6025.284211  walking

In [23]:
df1.mode = df1.mode.apply(lambda i: 0 if i == 'sitting' or i == 'standing' else 1)
df1.head()

          T301  mode
0  4762.852632     1
1  6321.615789     1
2  4269.086842     1
3  5315.044737     1
4  6025.284211     1

In [24]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 2 columns):
T301    97 non-null float64
mode    97 non-null int64
dtypes: float64(1), int64(1)
memory usage: 1.6 KB

In [39]:
x = np.array(df.T301)
y = np.array(df['mode']) 
x = x.reshape(-1, 1)

In [40]:
from sklearn.model_selection import train_test_split
seed = 2
test_size = 0.33
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=test_size, random_state=seed)
print (x_train.shape, x_test.shape, y_train.shape, y_test.shape)

ValueError: Found input variables with inconsistent numbers of samples: [1, 97]

In [34]:
import time
from sklearn.linear_model import LogisticRegression
LR_model = LogisticRegression()
start1 = time.time()
LR_model = LR_model.fit(x_train, y_train)
end1 = time.time()
LR_model.score(x_test, y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[1.51962105e+03 1.11973684e+01 4.96331842e+03 5.48344737e+03
 5.15526316e+00 5.18742105e+03 5.75018684e+03 4.39210526e+00
 3.62631579e+00 6.12368421e+00 2.88697368e+02 3.74355526e+03
 6.56315789e+00 4.70789474e+00 9.15263158e+00 4.77303158e+03
 3.02105263e+00 7.71435000e+03 6.16578947e+00 7.48947368e+00
 5.92776316e+02 8.46315790e+00 6.75531579e+02 2.66052632e+00
 4.29550263e+03 4.56052632e+00 4.51052632e+00 4.74473684e+00
 1.18394737e+01 1.04810737e+04 8.44736842e-01 3.88947368e+00
 9.30000000e+00 4.81315789e+00 3.24736842e+00 6.72226316e+02
 3.39473684e+00 4.03421053e+00 1.36842105e+00 5.30000000e+00
 9.62763158e+01 1.26092895e+03 4.65000000e+00 5.31286842e+02
 6.02528421e+03 4.60000000e+00 6.12907895e+02 5.40952632e+03
 3.28035790e+03 8.91407895e+02 5.86842105e+00 2.36617632e+03
 7.81578947e-01 1.97105263e+00 1.09447368e+01 3.12610526e+02
 5.61934210e+03 1.23421053e+00 4.92105263e+00 6.49434211e+02
 4.27903158e+03 2.87105263e+00 6.75964474e+03 1.31771316e+03].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.